version: '3.4'

services:
  slackbot.webhooks:
    image: ${DOCKER_REGISTRY-}slackbotwebhooks
    container_name: sb-webhooks
    build:
      context: .
      dockerfile: SlackBot.WebHooks/Dockerfile
    networks:
      - slackbot

  slackbot.getweather:
    image: ${DOCKER_REGISTRY-}slackbotgetweather
    container_name: sb-getweather
    build:
      context: .
      dockerfile: SlackBot.Services.GetWeather/Dockerfile
    networks:
      - slackbot

  ngrok:
    image: wernight/ngrok
    container_name: sb-ngrok
    ports:
      - 7001:4040
    environment:
      - NGROK_PORT=sb-webhooks:80
    networks:
      - slackbot

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sb-rabbitmq
    hostname: rabbit
    ports:
      - 7002:5672
      - 7003:15672
    networks:
      - slackbot

networks:
  slackbot:
    driver: bridge
